### ISSUE TITLE
Error: timed out while waiting for target halted

### ISSUE THREAD

**Issue by RickKimball** [vsergeev/arm-bmw-sw#1]
I've got an lpc1114fn28 connected to an stlink-v2 from a discovery board.
CN3 pins connected  1->VDD, 2->SWCLK, 3->GND, 4->SWDIO, 5-> reset, 6 -nc .. power to lpc1114 coming from the 3V pin on the discovery.

When I run it fails at the reset init function, if i remove that line and replace it with a halt,  I can then connect via arm-none-eabi-gdb and successfully load and debug.

Do I need to do anything special with the reset pin? I have an external pullup connected and pin 5 from the debug connector on the discovery board.

Thanks,
-rick

```
$ openocd -s openocd -f debug.cfg 
Open On-Chip Debugger 0.8.0-dev-00331-g1137eae (2014-01-25-15:17)
Licensed under GNU GPL v2
For bug reports, read
    http://openocd.sourceforge.net/doc/doxygen/bugs.html
srst_only separate srst_gates_jtag srst_open_drain connect_deassert_srst
Info : This adapter doesn't support configurable speed
Info : STLINK v2 JTAG v17 API v2 SWIM v0 VID 0x0483 PID 0x3748
Info : using stlink api v2
Info : Target voltage: 2.898221
Info : lpc1114.cpu: hardware has 4 breakpoints, 2 watchpoints
Error: timed out while waiting for target halted
TARGET: lpc1114.cpu - Not halted

Runtime Error: debug.cfg:9: 
in procedure 'script' 
at file "embedded:startup.tcl", line 58
in procedure 'reset' called at file "debug.cfg", line 9
$ 
```

**Comment by nathantsoi** [comment]
@RickKimball, you're my hero.

**Comment by sledgeh** [comment]
Thank you, @RickKimball!

**Comment by mquade** [comment]
@RickKimball man of the day!

**Comment by vishal-android-freak** [comment]
@RickKimball Thanks for the tip! :)

**Comment by DieHertz** [comment]
I have to use the `reset_config none separate` with my STLink v2 from BangGood, STM32F3Discovery as STLink works just fine with default reset_config :-( Why?

**Comment by FarisAlsaad** [comment]
@RickKimball THANK YOU!! The reset_config none separate works! But I had to go the the Debug Configurations -> Debugger tab -> Configuration Script and changed it to User Defined. When I added the line you recommended it did not work because when I press debug it overwrites the cfg file and puts back the original configuration that did not work. BTW I have the STM32F407VET6

**Comment by adadurov** [comment]
Based on the comment from @FarisAlsaad , the following worked for me and will hopefully work for other GUI users -- without the need to switch to 'user defined' configuration script.
Go to Debug Configurations -> Debugger tab -> Configuration Script -> Show generation options... -> Reset Mode ==> change to 'Software System Reset'.

**Comment by lWolvesl** [comment]
> 似乎处理这个问题的最简单方法就是使用
> 
> ```
> reset_config none separate
> ```
> 
> 然后在不使用引脚的情况下通过 SWD 通道在内部完成复位。

thanks !!!
